### ISSUE TITLE
ASSERT when running 'spdm_responder_emu.exe --cap CACHE'

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/spdm-emu#15]
Test at the commit https://github.com/DMTF/spdm-emu/commit/2c4ada81c43d740c345bdaac0a7da2796fec003a

Open one command prompt to run :
C:\spdm-emu\build\bin>spdm_responder_emu.exe --cap CACHE
spdm_responder_emu version 0.1
cap - 0x00000001
context_size - 0x7080
**ASSERT**: C:\spdm-emu\libspdm\library\spdm_common_lib\context_data.c(136): (*(uint32 *)data) & 0x00000002

**Comment by liyi77** [comment]
root cause: https://github.com/DMTF/libspdm/issues/205
it will cause false assertion when there is no CAP parameter based on the latest libspdm:

spdm_requester_emu version 0.1
trans - 0x1
connect success!
Platform port Transmit command: 00 00 de ad 
Platform port Transmit transport_type: 00 00 00 01 
Platform port Transmit size: 00 00 00 0e 
Platform port Transmit buffer:
    43 6c 69 65 6e 74 20 48 65 6c 6c 6f 21 00 
Platform port Receive command: 00 00 de ad 
Platform port Receive transport_type: 00 00 00 01 
Platform port Receive size: 00 00 00 0e 
Platform port Receive buffer:
    53 65 72 76 65 72 20 48 65 6c 6c 6f 21 00 
context_size - 0x1726c
data32: f7c6
**ASSERT**: E:\workspace\wp_spdm\spdm-emu\libspdm\library\spdm_common_lib\context_data.c(146): (*(uint32 *)data) & (0x00000008 | 0x00000010)
