### ISSUE TITLE
Does spdm-emu tool works over SMBUS/I2C lines?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/spdm-emu#45]
If it works over SMBUS/I2C lines, could you please provide the patch so that it will be helpful for me to run that tool inside Raspberry PI 3 Model B+ and we should be able to send and receive data over SMBUS/I2C lines between requester and responder.

**Comment by jyao1** [comment]
Emu is an OS application tool.
It does not support SMBUS/I2C line at this moment.

**Comment by PrakashK94** [comment]
ok thanks for your answer. I would like to know is there a plan to support SMBUS/I2C communication in future?

Also, the MCTP library which it is using does it support I2C/SMBUS communication?

**Comment by jyao1** [comment]
The emulator just sends MCTP message to network socket.

If you want to use this, you need write an SMBUS/I2C library to send message to SMBUS/I2C device.

We don't have plan at this moment. But you are welcome to contribute if you want.

**Comment by PrakashK94** [comment]
Thanks again. I will try replacing socket calls with I2C init, read, write functions and use the same MCTP library to check SMBUS/I2C communication, but before trying it out I would like to ask you is this the correct way to try this?

**Comment by jyao1** [comment]
right, you need write code to send data to SMBUS/I2C instead of network socket.

To be specific, you need implement libspdm_device_send_message_func() and libspdm_device_receive_message_func() declared in https://github.com/DMTF/libspdm/blob/main/include/library/spdm_common_lib.h. Then you need register them via libspdm_register_device_io_func().

You may search those 3 APIs, to see how they are used or implemented in spdm-emu.
